# Docker image to be used
image:
    repository: quay.io/heubeck/statuspage-prometheus-exporter
    tag: 0.0.1

# Exposing Service configuration
service:
    type: ClusterIP
    port: 80

# ServiceMonitor resource for CoreOS Prometheus Operator, provides exporter auto-detection
serviceMonitor:
    enabled: true
    namespace: monitoring

# Content of the configuration file korry.yaml
configuration:
     - name: "Github"
       url: "kctbh9vrtdwd.statuspage.io"
     - name: "Quay.io"
       url: "8szqd6w4s277.statuspage.io"
