apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
data:
    config.json: |
        [
        {{- range $i, $e := .Values.configuration -}}
        {{if $i }}, {{end}}
        {
            "name": "{{- $e.name -}}",
            "url": "{{- $e.url -}}"
        }
        {{- end -}}
        ]
