apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app: {{ .Release.Name }}
        version: {{ .Values.image.tag }}
    annotations:
        release/time: {{ date "2006-01-02T15:04:05Z07:00" now }}
        release/revision: "{{ .Release.Revision }}"
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ .Release.Name }}
            app.kubernetes.io/instance: {{ .Release.Name }}
    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{ .Release.Name }}
                app.kubernetes.io/instance: {{ .Release.Name }}
                app: {{ .Release.Name }}
                version: {{ .Values.image.tag }}
        spec:
            containers:
                - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
                  name: {{ .Release.Name }}
                  imagePullPolicy: IfNotPresent
                  env:
                      - name: STATUS_CONFIG_FILE
                        value: /config/config.json
                  volumeMounts:
                      - name: config
                        mountPath: /config
                        readOnly: true
                  livenessProbe:
                      failureThreshold: 2
                      httpGet:
                          path: /live
                          port: 8080
                          scheme: HTTP
                      periodSeconds: 30
                      successThreshold: 1
                      timeoutSeconds: 1
                  resources:
                      limits:
                          cpu: 100m
                          memory: 100M
                      requests:
                          cpu: 10m
                          memory: 10M
                  ports:
                      - name: http
                        containerPort: 8080
                        protocol: TCP
            volumes:
                - name: config
                  configMap:
                      name: {{ .Release.Name }}
